/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'page-content': PageContent;
    'home-page': HomePage;
    'about-page': AboutPage;
    'courses-page': CoursesPage;
    'instructors-page': InstructorsPage;
    'pricing-page': PricingPage;
    'blog-page': BlogPage;
    'blog-details-page': BlogDetailsPage;
    'contact-page': ContactPage;
    'enroll-page': EnrollPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'page-content': PageContentSelect<false> | PageContentSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'courses-page': CoursesPageSelect<false> | CoursesPageSelect<true>;
    'instructors-page': InstructorsPageSelect<false> | InstructorsPageSelect<true>;
    'pricing-page': PricingPageSelect<false> | PricingPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'blog-details-page': BlogDetailsPageSelect<false> | BlogDetailsPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'enroll-page': EnrollPageSelect<false> | EnrollPageSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage all website pages - create new pages by selecting a page type
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content".
 */
export interface PageContent {
  id: string;
  /**
   * Select the type of page you want to create
   */
  pageType:
    | 'home-page'
    | 'about-page'
    | 'courses-page'
    | 'instructors-page'
    | 'pricing-page'
    | 'blog-page'
    | 'blog-details-page'
    | 'contact-page'
    | 'enroll-page'
    | 'custom-page';
  /**
   * Enter the title/name for this page
   */
  pageTitle: string;
  /**
   * URL slug for this page (e.g., "about-us", "pricing")
   */
  pageSlug: string;
  status: 'draft' | 'published' | 'archived';
  /**
   * Redirect users to the appropriate page collection based on page type
   */
  redirectTo?: {
    /**
     * Instructions for page creation workflow
     */
    instructions?: string | null;
  };
  /**
   * Fields for custom pages that don't fit standard page types
   */
  customPageData?: {
    title?: string | null;
    subtitle?: string | null;
    description?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
    secondaryButtonText?: string | null;
    secondaryButtonLink?: string | null;
    image?: (string | null) | Media;
    backgroundImage?: (string | null) | Media;
  };
  /**
   * Statistics/numbers for custom pages
   */
  customStats?:
    | {
        number?: string | null;
        label?: string | null;
        /**
         * Bootstrap icon class (e.g., "bi-people")
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Feature items for custom pages
   */
  customFeatures?:
    | {
        title?: string | null;
        description?: string | null;
        /**
         * Bootstrap icon class
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional custom fields for unique requirements
   */
  customData?:
    | {
        fieldName?: string | null;
        fieldValue?: string | null;
        fieldType?: ('text' | 'number' | 'url' | 'email' | 'json') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  /**
   * Name to identify this section (e.g., "Hero Section", "Featured Courses")
   */
  sectionName: string;
  /**
   * Select the section type
   */
  sectionType:
    | 'hero'
    | 'featured-courses'
    | 'course-categories'
    | 'featured-instructors'
    | 'testimonials'
    | 'blog-posts'
    | 'cta';
  status: 'active' | 'inactive';
  hero?: {
    title: string;
    description: string;
    heroImage: string | Media;
    stats?:
      | {
          number: number;
          label: string;
          id?: string | null;
        }[]
      | null;
    primaryButton: {
      text: string;
      link: string;
    };
    secondaryButton: {
      text: string;
      link: string;
    };
    features?:
      | {
          icon: 'bi-shield-check' | 'bi-clock' | 'bi-people' | 'bi-award' | 'bi-book' | 'bi-star';
          text: string;
          id?: string | null;
        }[]
      | null;
    floatingCards?:
      | {
          icon: 'bi-code-slash' | 'bi-palette' | 'bi-graph-up' | 'bi-laptop' | 'bi-camera' | 'bi-briefcase';
          title: string;
          students: string;
          id?: string | null;
        }[]
      | null;
  };
  featuredCourses?: {
    title: string;
    description: string;
    courses?:
      | {
          image: string | Media;
          badge?: ('featured' | 'new' | 'certificate' | 'popular') | null;
          price: string;
          level: 'Beginner' | 'Intermediate' | 'Advanced';
          duration: string;
          title: string;
          description: string;
          instructorAvatar: string | Media;
          instructorName: string;
          instructorSpecialty: string;
          rating: number;
          studentCount: number;
          id?: string | null;
        }[]
      | null;
    viewAllButton?: {
      text?: string | null;
      link?: string | null;
    };
  };
  courseCategories?: {
    title: string;
    description: string;
    categories?:
      | {
          icon:
            | 'bi-laptop'
            | 'bi-briefcase'
            | 'bi-palette'
            | 'bi-heart-pulse'
            | 'bi-globe'
            | 'bi-diagram-3'
            | 'bi-megaphone'
            | 'bi-graph-up-arrow'
            | 'bi-camera'
            | 'bi-music-note-beamed'
            | 'bi-gear'
            | 'bi-journal-text'
            | 'bi-cup-hot'
            | 'bi-trophy'
            | 'bi-pen'
            | 'bi-body-text'
            | 'bi-tree'
            | 'bi-chat-dots';
          name: string;
          courseCount: number;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  featuredInstructors?: {
    title: string;
    description: string;
    instructors?:
      | {
          image: string | Media;
          name: string;
          specialty: string;
          description: string;
          rating: number;
          courseCount: number;
          studentCount: number;
          socialLinks?:
            | {
                platform?:
                  | ('linkedin' | 'twitter' | 'github' | 'dribbble' | 'behance' | 'instagram' | 'facebook')
                  | null;
                url: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  testimonials?: {
    title: string;
    description: string;
    criticReviews?:
      | {
          source: string;
          rating: number;
          quote: string;
          id?: string | null;
        }[]
      | null;
    studentReviews?:
      | {
          avatar: string | Media;
          name: string;
          role: string;
          rating: number;
          review: string;
          id?: string | null;
        }[]
      | null;
    overallRating: {
      rating: number;
      reviewCount: string;
      platforms?:
        | {
            name: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  blogPosts?: {
    title: string;
    description: string;
    posts?:
      | {
          authorAvatar: string | Media;
          authorName: string;
          likes: number;
          image: string | Media;
          title: string;
          excerpt: string;
          link: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    title: string;
    description: string;
    image: string | Media;
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    primaryButton: {
      text: string;
      link: string;
    };
    secondaryButton: {
      text: string;
      link: string;
    };
    stats?:
      | {
          number: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    floatingCards?:
      | {
          icon?: ('bi-person-check-fill' | 'bi-play-circle-fill' | 'bi-award-fill' | 'bi-check-circle-fill') | null;
          number: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  /**
   * Name to identify this section (e.g., "Page Title", "About Main")
   */
  sectionName: string;
  /**
   * Select the section type
   */
  sectionType: 'page-title' | 'about-main' | 'mission-vision-values' | 'why-choose-us';
  status: 'active' | 'inactive';
  pageTitle?: {
    title: string;
    breadcrumbs?:
      | {
          label: string;
          link?: string | null;
          isActive?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  aboutMain?: {
    image: string | Media;
    subtitle: string;
    title: string;
    description: string;
    stats?:
      | {
          count: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  missionVisionValues?: {
    cards?:
      | {
          icon: 'bi-bullseye' | 'bi-eye' | 'bi-award' | 'bi-target' | 'bi-lightbulb' | 'bi-heart';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  whyChooseUs?: {
    subtitle: string;
    title: string;
    description: string;
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    buttonText: string;
    buttonLink: string;
    galleryImages?:
      | {
          image: string | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page".
 */
export interface CoursesPage {
  id: string;
  sectionName: string;
  sectionType: 'page-title' | 'filters' | 'courses-grid';
  status: 'active' | 'inactive';
  pageTitle?: {
    title: string;
    breadcrumbs?:
      | {
          label: string;
          link?: string | null;
          isActive?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  filters?: {
    title: string;
    categoryFilters?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    levelFilters?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    durationFilters?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    priceFilters?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  coursesGrid?: {
    searchPlaceholder?: string | null;
    sortOptions?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    courses?:
      | {
          image: string | Media;
          badge?: ('none' | 'best-seller' | 'new' | 'popular' | 'free' | 'certificate') | null;
          price: string;
          category: string;
          level: 'Beginner' | 'Intermediate' | 'Advanced';
          title: string;
          description: string;
          duration: string;
          studentCount: string;
          rating: number;
          reviewCount: number;
          instructorAvatar: string | Media;
          instructorName: string;
          enrollLink?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors-page".
 */
export interface InstructorsPage {
  id: string;
  sectionName: string;
  sectionType: 'page-title' | 'instructors-grid';
  status: 'active' | 'inactive';
  pageTitle?: {
    title: string;
    breadcrumbs?:
      | {
          label: string;
          link?: string | null;
          isActive?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  instructorsGrid?: {
    instructors?:
      | {
          image: string | Media;
          name: string;
          specialty: string;
          description: string;
          rating: number;
          courseCount: number;
          /**
           * e.g., "2.1k" or "2100"
           */
          studentCount: string;
          profileLink?: string | null;
          socialLinks?:
            | {
                platform?:
                  | (
                      | 'linkedin'
                      | 'twitter'
                      | 'github'
                      | 'dribbble'
                      | 'behance'
                      | 'instagram'
                      | 'facebook'
                      | 'youtube'
                      | 'shield-check'
                      | 'cloud'
                    )
                  | null;
                url: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page".
 */
export interface PricingPage {
  id: string;
  sectionName: string;
  sectionType: 'page-title' | 'pricing-section';
  status: 'active' | 'inactive';
  pageTitle?: {
    title: string;
    breadcrumbs?:
      | {
          label: string;
          link?: string | null;
          isActive?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  pricingSection?: {
    toggleLabels?: {
      monthlyLabel?: string | null;
      yearlyLabel?: string | null;
      yearlyBadge?: string | null;
    };
    pricingPlans?:
      | {
          planName: string;
          description: string;
          isPopular?: boolean | null;
          popularBadge?: string | null;
          priceType: 'free' | 'monthly-yearly' | 'custom';
          monthlyPrice?: number | null;
          yearlyPrice?: number | null;
          ctaText: string;
          ctaLink: string;
          featuresHeading: string;
          features?:
            | {
                text: string;
                isHighlight?: boolean | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: string;
  /**
   * Internal name for this section (e.g., "Blog Page Title", "Hero Posts Grid")
   */
  sectionName: string;
  /**
   * Select the type of section
   */
  sectionType: 'page-title' | 'blog-hero' | 'blog-posts';
  status: 'active' | 'inactive';
  pageTitle?: {
    title: string;
    breadcrumbs?:
      | {
          label: string;
          link?: string | null;
          isActive?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  blogHero?: {
    /**
     * First post will be featured (large), rest will be regular size
     */
    posts?:
      | {
          image: string | Media;
          /**
           * e.g., "Apr. 14th, 2025"
           */
          date: string;
          /**
           * e.g., "Technology", "Security", "Career"
           */
          category: string;
          title: string;
          link: string;
          id?: string | null;
        }[]
      | null;
  };
  blogPosts?: {
    posts?:
      | {
          image: string | Media;
          date: {
            /**
             * e.g., 12
             */
            day: number;
            /**
             * e.g., "December"
             */
            month: string;
          };
          /**
           * e.g., "John Doe"
           */
          author: string;
          /**
           * e.g., "Politics", "Economics", "Sports"
           */
          category: string;
          title: string;
          link: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-details-page".
 */
export interface BlogDetailsPage {
  id: string;
  /**
   * Internal name for this section (e.g., "Blog Details Page Title", "Article Content")
   */
  sectionName: string;
  /**
   * Select the type of section
   */
  sectionType: 'page-title' | 'article-header' | 'article-content' | 'comments';
  status: 'active' | 'inactive';
  pageTitle?: {
    title: string;
    breadcrumbs?:
      | {
          label: string;
          link?: string | null;
          isActive?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  articleHeader?: {
    /**
     * Article categories/tags shown above title
     */
    categories?:
      | {
          name: string;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Main article title
     */
    title: string;
    author: {
      image: string | Media;
      name: string;
      role: string;
    };
    postInfo: {
      /**
       * e.g., "April 15, 2025"
       */
      date: string;
      /**
       * e.g., "10 min read"
       */
      readTime: string;
      commentsCount: number;
    };
    featuredImage: string | Media;
    /**
     * Table of contents items
     */
    tableOfContents?:
      | {
          label: string;
          /**
           * Anchor ID without # (e.g., "introduction")
           */
          anchor: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Related topic tags shown at bottom
     */
    tags?:
      | {
          name: string;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  articleContent?: {
    /**
     * Content sections of the article
     */
    sections?:
      | {
          /**
           * ID for anchor linking (e.g., "introduction")
           */
          sectionId: string;
          /**
           * Section heading (optional for introduction)
           */
          heading?: string | null;
          content: string;
          hasQuote?: boolean | null;
          quote?: {
            text: string;
            author: string;
          };
          hasImage?: boolean | null;
          image?: {
            file: string | Media;
            caption?: string | null;
            position?: ('left' | 'right' | 'center') | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  comments?: {
    heading?: string | null;
    totalComments: number;
    /**
     * Top-level comments with optional replies
     */
    commentThreads?:
      | {
          avatar: string | Media;
          authorName: string;
          /**
           * e.g., "2 hours ago"
           */
          timeAgo: string;
          likes?: number | null;
          commentText: string;
          /**
           * Nested replies to this comment
           */
          replies?:
            | {
                avatar: string | Media;
                authorName: string;
                timeAgo: string;
                likes?: number | null;
                commentText: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  /**
   * Internal name for this section (e.g., "Contact Page Title", "Contact Information")
   */
  sectionName: string;
  /**
   * Select the type of section
   */
  sectionType: 'page-title' | 'contact-map' | 'contact-info';
  status: 'active' | 'inactive';
  pageTitle?: {
    title: string;
    breadcrumbs?:
      | {
          label: string;
          link?: string | null;
          isActive?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  contactMap?: {
    /**
     * Google Maps embed URL
     */
    mapEmbedUrl: string;
  };
  contactInfo?: {
    /**
     * Contact information cards
     */
    contactCards?:
      | {
          icon: 'bi-geo-alt' | 'bi-envelope' | 'bi-telephone' | 'bi-clock' | 'bi-calendar' | 'bi-chat-dots';
          /**
           * e.g., "Location", "Email", "Call"
           */
          heading: string;
          /**
           * Contact information text
           */
          text: string;
          id?: string | null;
        }[]
      | null;
    formSection: {
      heading: string;
      description: string;
      /**
       * Form submission endpoint
       */
      formAction: string;
      submitButtonText: string;
      /**
       * Social media links shown below submit button
       */
      socialLinks?:
        | {
            platform: 'twitter' | 'facebook' | 'instagram' | 'linkedin' | 'youtube';
            url: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enroll-page".
 */
export interface EnrollPage {
  id: string;
  /**
   * Internal name for this section (e.g., "Enroll Page Title", "Enrollment Form")
   */
  sectionName: string;
  /**
   * Select the type of section
   */
  sectionType: 'page-title' | 'enrollment-form' | 'benefits-sidebar';
  status: 'active' | 'inactive';
  pageTitle?: {
    title: string;
    breadcrumbs?:
      | {
          label: string;
          link?: string | null;
          isActive?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  enrollmentForm?: {
    header: {
      heading: string;
      description: string;
    };
    /**
     * Available courses in the dropdown
     */
    courseOptions?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Education level options
     */
    educationLevels?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Experience level options
     */
    experienceLevels?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Learning schedule options
     */
    scheduleOptions?:
      | {
          label: string;
          value: string;
          isDefault?: boolean | null;
          id?: string | null;
        }[]
      | null;
    submitButton: {
      text: string;
      icon?: ('bi-check-circle' | 'bi-arrow-right' | 'bi-send') | null;
    };
    securityNote: string;
  };
  benefitsSidebar?: {
    heading: string;
    /**
     * Benefits list
     */
    benefits?:
      | {
          icon:
            | 'bi-trophy'
            | 'bi-clock'
            | 'bi-award'
            | 'bi-people'
            | 'bi-star'
            | 'bi-book'
            | 'bi-lightbulb'
            | 'bi-shield-check';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Statistics to display
     */
    stats?:
      | {
          /**
           * e.g., "15,000+", "98%", "4.9/5"
           */
          number: string;
          /**
           * e.g., "Students Enrolled", "Completion Rate"
           */
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'page-content';
        value: string | PageContent;
      } | null)
    | ({
        relationTo: 'home-page';
        value: string | HomePage;
      } | null)
    | ({
        relationTo: 'about-page';
        value: string | AboutPage;
      } | null)
    | ({
        relationTo: 'courses-page';
        value: string | CoursesPage;
      } | null)
    | ({
        relationTo: 'instructors-page';
        value: string | InstructorsPage;
      } | null)
    | ({
        relationTo: 'pricing-page';
        value: string | PricingPage;
      } | null)
    | ({
        relationTo: 'blog-page';
        value: string | BlogPage;
      } | null)
    | ({
        relationTo: 'blog-details-page';
        value: string | BlogDetailsPage;
      } | null)
    | ({
        relationTo: 'contact-page';
        value: string | ContactPage;
      } | null)
    | ({
        relationTo: 'enroll-page';
        value: string | EnrollPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content_select".
 */
export interface PageContentSelect<T extends boolean = true> {
  pageType?: T;
  pageTitle?: T;
  pageSlug?: T;
  status?: T;
  redirectTo?:
    | T
    | {
        instructions?: T;
      };
  customPageData?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
        image?: T;
        backgroundImage?: T;
      };
  customStats?:
    | T
    | {
        number?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  customFeatures?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  customData?:
    | T
    | {
        fieldName?: T;
        fieldValue?: T;
        fieldType?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  sectionName?: T;
  sectionType?: T;
  status?: T;
  hero?:
    | T
    | {
        title?: T;
        description?: T;
        heroImage?: T;
        stats?:
          | T
          | {
              number?: T;
              label?: T;
              id?: T;
            };
        primaryButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
        secondaryButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
        features?:
          | T
          | {
              icon?: T;
              text?: T;
              id?: T;
            };
        floatingCards?:
          | T
          | {
              icon?: T;
              title?: T;
              students?: T;
              id?: T;
            };
      };
  featuredCourses?:
    | T
    | {
        title?: T;
        description?: T;
        courses?:
          | T
          | {
              image?: T;
              badge?: T;
              price?: T;
              level?: T;
              duration?: T;
              title?: T;
              description?: T;
              instructorAvatar?: T;
              instructorName?: T;
              instructorSpecialty?: T;
              rating?: T;
              studentCount?: T;
              id?: T;
            };
        viewAllButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
      };
  courseCategories?:
    | T
    | {
        title?: T;
        description?: T;
        categories?:
          | T
          | {
              icon?: T;
              name?: T;
              courseCount?: T;
              link?: T;
              id?: T;
            };
      };
  featuredInstructors?:
    | T
    | {
        title?: T;
        description?: T;
        instructors?:
          | T
          | {
              image?: T;
              name?: T;
              specialty?: T;
              description?: T;
              rating?: T;
              courseCount?: T;
              studentCount?: T;
              socialLinks?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        title?: T;
        description?: T;
        criticReviews?:
          | T
          | {
              source?: T;
              rating?: T;
              quote?: T;
              id?: T;
            };
        studentReviews?:
          | T
          | {
              avatar?: T;
              name?: T;
              role?: T;
              rating?: T;
              review?: T;
              id?: T;
            };
        overallRating?:
          | T
          | {
              rating?: T;
              reviewCount?: T;
              platforms?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
            };
      };
  blogPosts?:
    | T
    | {
        title?: T;
        description?: T;
        posts?:
          | T
          | {
              authorAvatar?: T;
              authorName?: T;
              likes?: T;
              image?: T;
              title?: T;
              excerpt?: T;
              link?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        primaryButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
        secondaryButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
        stats?:
          | T
          | {
              number?: T;
              label?: T;
              id?: T;
            };
        floatingCards?:
          | T
          | {
              icon?: T;
              number?: T;
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  sectionName?: T;
  sectionType?: T;
  status?: T;
  pageTitle?:
    | T
    | {
        title?: T;
        breadcrumbs?:
          | T
          | {
              label?: T;
              link?: T;
              isActive?: T;
              id?: T;
            };
      };
  aboutMain?:
    | T
    | {
        image?: T;
        subtitle?: T;
        title?: T;
        description?: T;
        stats?:
          | T
          | {
              count?: T;
              label?: T;
              id?: T;
            };
      };
  missionVisionValues?:
    | T
    | {
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  whyChooseUs?:
    | T
    | {
        subtitle?: T;
        title?: T;
        description?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        buttonText?: T;
        buttonLink?: T;
        galleryImages?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page_select".
 */
export interface CoursesPageSelect<T extends boolean = true> {
  sectionName?: T;
  sectionType?: T;
  status?: T;
  pageTitle?:
    | T
    | {
        title?: T;
        breadcrumbs?:
          | T
          | {
              label?: T;
              link?: T;
              isActive?: T;
              id?: T;
            };
      };
  filters?:
    | T
    | {
        title?: T;
        categoryFilters?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        levelFilters?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        durationFilters?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        priceFilters?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  coursesGrid?:
    | T
    | {
        searchPlaceholder?: T;
        sortOptions?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        courses?:
          | T
          | {
              image?: T;
              badge?: T;
              price?: T;
              category?: T;
              level?: T;
              title?: T;
              description?: T;
              duration?: T;
              studentCount?: T;
              rating?: T;
              reviewCount?: T;
              instructorAvatar?: T;
              instructorName?: T;
              enrollLink?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors-page_select".
 */
export interface InstructorsPageSelect<T extends boolean = true> {
  sectionName?: T;
  sectionType?: T;
  status?: T;
  pageTitle?:
    | T
    | {
        title?: T;
        breadcrumbs?:
          | T
          | {
              label?: T;
              link?: T;
              isActive?: T;
              id?: T;
            };
      };
  instructorsGrid?:
    | T
    | {
        instructors?:
          | T
          | {
              image?: T;
              name?: T;
              specialty?: T;
              description?: T;
              rating?: T;
              courseCount?: T;
              studentCount?: T;
              profileLink?: T;
              socialLinks?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page_select".
 */
export interface PricingPageSelect<T extends boolean = true> {
  sectionName?: T;
  sectionType?: T;
  status?: T;
  pageTitle?:
    | T
    | {
        title?: T;
        breadcrumbs?:
          | T
          | {
              label?: T;
              link?: T;
              isActive?: T;
              id?: T;
            };
      };
  pricingSection?:
    | T
    | {
        toggleLabels?:
          | T
          | {
              monthlyLabel?: T;
              yearlyLabel?: T;
              yearlyBadge?: T;
            };
        pricingPlans?:
          | T
          | {
              planName?: T;
              description?: T;
              isPopular?: T;
              popularBadge?: T;
              priceType?: T;
              monthlyPrice?: T;
              yearlyPrice?: T;
              ctaText?: T;
              ctaLink?: T;
              featuresHeading?: T;
              features?:
                | T
                | {
                    text?: T;
                    isHighlight?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  sectionName?: T;
  sectionType?: T;
  status?: T;
  pageTitle?:
    | T
    | {
        title?: T;
        breadcrumbs?:
          | T
          | {
              label?: T;
              link?: T;
              isActive?: T;
              id?: T;
            };
      };
  blogHero?:
    | T
    | {
        posts?:
          | T
          | {
              image?: T;
              date?: T;
              category?: T;
              title?: T;
              link?: T;
              id?: T;
            };
      };
  blogPosts?:
    | T
    | {
        posts?:
          | T
          | {
              image?: T;
              date?:
                | T
                | {
                    day?: T;
                    month?: T;
                  };
              author?: T;
              category?: T;
              title?: T;
              link?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-details-page_select".
 */
export interface BlogDetailsPageSelect<T extends boolean = true> {
  sectionName?: T;
  sectionType?: T;
  status?: T;
  pageTitle?:
    | T
    | {
        title?: T;
        breadcrumbs?:
          | T
          | {
              label?: T;
              link?: T;
              isActive?: T;
              id?: T;
            };
      };
  articleHeader?:
    | T
    | {
        categories?:
          | T
          | {
              name?: T;
              link?: T;
              id?: T;
            };
        title?: T;
        author?:
          | T
          | {
              image?: T;
              name?: T;
              role?: T;
            };
        postInfo?:
          | T
          | {
              date?: T;
              readTime?: T;
              commentsCount?: T;
            };
        featuredImage?: T;
        tableOfContents?:
          | T
          | {
              label?: T;
              anchor?: T;
              id?: T;
            };
        tags?:
          | T
          | {
              name?: T;
              link?: T;
              id?: T;
            };
      };
  articleContent?:
    | T
    | {
        sections?:
          | T
          | {
              sectionId?: T;
              heading?: T;
              content?: T;
              hasQuote?: T;
              quote?:
                | T
                | {
                    text?: T;
                    author?: T;
                  };
              hasImage?: T;
              image?:
                | T
                | {
                    file?: T;
                    caption?: T;
                    position?: T;
                  };
              id?: T;
            };
      };
  comments?:
    | T
    | {
        heading?: T;
        totalComments?: T;
        commentThreads?:
          | T
          | {
              avatar?: T;
              authorName?: T;
              timeAgo?: T;
              likes?: T;
              commentText?: T;
              replies?:
                | T
                | {
                    avatar?: T;
                    authorName?: T;
                    timeAgo?: T;
                    likes?: T;
                    commentText?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  sectionName?: T;
  sectionType?: T;
  status?: T;
  pageTitle?:
    | T
    | {
        title?: T;
        breadcrumbs?:
          | T
          | {
              label?: T;
              link?: T;
              isActive?: T;
              id?: T;
            };
      };
  contactMap?:
    | T
    | {
        mapEmbedUrl?: T;
      };
  contactInfo?:
    | T
    | {
        contactCards?:
          | T
          | {
              icon?: T;
              heading?: T;
              text?: T;
              id?: T;
            };
        formSection?:
          | T
          | {
              heading?: T;
              description?: T;
              formAction?: T;
              submitButtonText?: T;
              socialLinks?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enroll-page_select".
 */
export interface EnrollPageSelect<T extends boolean = true> {
  sectionName?: T;
  sectionType?: T;
  status?: T;
  pageTitle?:
    | T
    | {
        title?: T;
        breadcrumbs?:
          | T
          | {
              label?: T;
              link?: T;
              isActive?: T;
              id?: T;
            };
      };
  enrollmentForm?:
    | T
    | {
        header?:
          | T
          | {
              heading?: T;
              description?: T;
            };
        courseOptions?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        educationLevels?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        experienceLevels?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        scheduleOptions?:
          | T
          | {
              label?: T;
              value?: T;
              isDefault?: T;
              id?: T;
            };
        submitButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
        securityNote?: T;
      };
  benefitsSidebar?:
    | T
    | {
        heading?: T;
        benefits?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              number?: T;
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  siteName: string;
  siteDescription?: string | null;
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zipCode?: string | null;
    country?: string | null;
  };
  businessHours?: string | null;
  socialLinks?: {
    facebook?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
  };
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultMetaImage?: (string | null) | Media;
  googleAnalyticsId?: string | null;
  footerText?: string | null;
  copyrightText?: string | null;
  footerLinks?:
    | {
        title?: string | null;
        links?:
          | {
              label?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        country?: T;
      };
  businessHours?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
      };
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultMetaImage?: T;
  googleAnalyticsId?: T;
  footerText?: T;
  copyrightText?: T;
  footerLinks?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}